### ISSUE TITLE
fokus_auth

### ISSUE THREAD

**Issue by hackerspace-team** [fokus-team/fokus#84]
Could not find a file named "pubspec.yaml" in "fokus-master/fokus_auth".

**Comment by stasgora** [comment]
Hi, thanks for your interest in Fokus!

Unfortunately at this time we do not provide an option to externally build our app as this would require setting up a complex environment. Our backend services include OneSignal, MongoDB and Firebase (that on itself would require a fair bit of configuration) so it would be hard for anyone to recreate the required environment.
